### ISSUE TITLE
Snap cannot load fonts on Manjaro

### ISSUE THREAD

**Issue by richarddribeiro** [ariejan/txdx#2] opened 2022-04-30 22:22 UTC
**Describe the bug**
When we try to select the TxDx folder, the window the appears has a problem with the font. No letters appears, just small squares in their places.

**To Reproduce**
1. Launch TxDx app
2. Click on 'Select your TxDx folder'
3. See the error

**Expected behavior**
It should be a window with text that one could use to select the correct todo.txt folder/file.

**Screenshots**
![txdx-font-problem](https://user-images.githubusercontent.com/47891600/166124405-74d08a82-72d3-4465-9cea-a07e6f5e85a8.png)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro

**Additional context**
I already tried to find information about that in the internet, and it seems that it is a quite common problem with snap apps. Unfortunately none of the proposed solutions worked. 

I would like to test TxDx, but with that problem it is not possible to do it.

Thanks for looking at it.

**Comment by ariejan** [comment] 2022-05-01 07:04
Thanks for letting me know! I found a few posts myself about this. I'll spin up a Manjaro VM and see if I can reproduce this. 

In the meantime, I don't know if you've already tried clearing your font cache:

    $ sudo rm -f /var/cache/fontconfig/*
    $ rm -f ~/.cache/fontconfig

If all else fails, what would be an acceptable alternative to Snap to you? I'm considering AppImage and `.deb` right now.

**Comment by ariejan** [comment] 2022-05-01 07:12
For reference, [this thread](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484) on the snapcraft forum has been discussing this issue since July 2019 - with no fix in sight. 😞

**Comment by ariejan** [comment] 2022-05-01 07:20
[This ColourPicker issue](https://github.com/stuartlangridge/ColourPicker/issues/60) discusses the same thing. A fix seems to be to update you systems `fonts.conf`. I'm not recommending this, as I don't know if it will mess up your system or not, just so you know.

**Comment by richarddribeiro** [comment] 2022-05-01 14:26
Hi Ariejan,

Thank you for your time looking for the issue.

Similarly to you, I've tried clearing my font cache, but the problem persisted. Also, I spent some time in the snapcraft forum searching for a solution, but none of the proposed ones worked for me. The ColourPicker tip seems too radical, so I decided to avoid it for the moment.

If you decide to try the AUR packing when you have some time free it would be great! I would be more than happy testing it, if you agree.

Again, thank your time looking for this, and for creating a software that has a great potential to be part of our daily routine.

All the best.

**Comment by ariejan** [comment] 2022-05-01 19:30
@richarddribeiro https://aur.archlinux.org/packages/txdx

Feel free to check that out. It still builds from source for now. Once I get it hooked up to CI I'll add the `-bin` version as well to speed things up for you. This version does _not_ have any of the Snap issues you reported, btw. 

Looking to hearing what you think of the app!

PS. I'm closing this issue, because I can't single-handedly fix Snap. For any others viewing this, full AUR and deb support is on my, erm, todo list.

**Closed by ariejan** 2022-05-01 19:30 UTC
Labels: bug

**Comment by richarddribeiro** [comment] 2022-05-01 20:44
Hi Ariejan,

Thank you for making TxDx available through AUR. I already have installed a few programs from there, and usually it is the first place I look for when something is not available in Manjaro Official Repositories.

So, as usual, I used `yay` to try install TxDx, like that:
`yay -S txdx`

But unfortunately I got an error:
> [...]
> ==> Starting prepare()...
> /home/richard/.cache/yay/txdx/PKGBUILD: line 16: flutter: command not found
> ==> ERROR: A failure occurred in prepare().
>     Aborting...
>  -> error making: txdx

The message is clearly saying that it needs flutter to correctly install it, but because I am trying to make easy for others to try TxDx, I decided to not do so and instead check with you if flutter needs to be included as a dependency within the program.

All the best,
Richard

**Comment by ariejan** [comment] 2022-05-02 07:02
Hmz. I _do_ have `flutter-beta` in `makedepends`. Maybe that's not the right place. I'm not sure how well-versed you are in AUR packages, but I'm taking another look. 

Ref: https://gitlab.devroom.io/ariejan/txdx/-/blob/master/PKGBUILD#L9

**Comment by ariejan** [comment] 2022-05-02 07:03
🤦 `makepends`

**Comment by ariejan** [comment] 2022-05-02 07:24
@richarddribeiro can you try that again? I reverted my VM to a prestine Manjaro 21.2.6 version and install with `yay -S txdx` now works as expected (e.g. installing the make dependencies).

**Comment by ariejan** [comment] 2022-05-03 11:26
@richarddribeiro there's not also a `txdx-bin` AUR package that avoids the whole "compile from source" complexity. `yay -S txdx-bin` should do the trick.
